Authentication
SparkChats/API pull request #12
Opened 2023-08-01 15:10 UTC by Grabtot

2023-08-01 17:21 UTC, ArtCrafter2999 requested changes
Написав баги на які наткнувся

2023-08-01 17:21 UTC, ArtCrafter2999 commented on Identity/RequestHandlers/LoginRequestHandler.cs
> +            IdentityUser user = await _userManager.FindByEmailAsync(request.Email);
Якщо юзера з таким email не знайдено, то воно повертає exeption

2023-08-01 17:21 UTC, ArtCrafter2999 commented on Identity/Views/Authentication/Login.cshtml
> +       asp-route-returnUrl="@Model.ReturnUrl">Register</a>
Кнопка Register нікуди не перенаправляє

2023-08-01 17:21 UTC, ArtCrafter2999 commented on Identity/Views/Authentication/Register.cshtml
> +    <a asp-controller="Authorization" asp-action="Login" asp-route-returnUrl="@Model.ReturnUrl">Login</a>
кнопка Login нікуди не перенаправляє

2023-08-01 17:21 UTC, ArtCrafter2999 commented on Identity/Controllers/AuthenticationController.cs
> +                return View(registrationRequest);
по данним ніби все правильно, але відправляє мене на цю строчку і навіть не пояснює що не так
![image](https://github.com/NewDiscordClone/API/assets/92592800/f16339bf-ede4-495b-906c-96786561c127)
Edit: я додав знак оклику в пароль і воно все одно мене закидує в цю секцію коду, але якщо скіпати то нормально реєструє

2023-08-01 18:30 UTC, Grabtot commented on Identity/RequestHandlers/LoginRequestHandler.cs
> +            IdentityUser user = await _userManager.FindByEmailAsync(request.Email);
Точно, забыл это допилить

2023-08-02 14:08 UTC, Grabtot commented on Identity/RequestHandlers/LoginRequestHandler.cs
> +            IdentityUser user = await _userManager.FindByEmailAsync(request.Email);
Добавил проверку

2023-08-02 14:08 UTC, Grabtot commented on Identity/Views/Authentication/Login.cshtml
> +       asp-route-returnUrl="@Model.ReturnUrl">Register</a>
Изменил имя контроллера на правильное

2023-08-02 14:08 UTC, Grabtot commented on Identity/Views/Authentication/Register.cshtml
> +    <a asp-controller="Authorization" asp-action="Login" asp-route-returnUrl="@Model.ReturnUrl">Login</a>
Изменил имя контроллера на правильное

2023-08-02 14:09 UTC, Grabtot commented on Identity/Controllers/AuthenticationController.cs
> +                return View(registrationRequest);
Тут я забыл добавить стоку для ввода ConfirmPassword

2023-08-02 14:13 UTC, Grabtot commented on Identity/Controllers/AuthenticationController.cs
> +                return View(registrationRequest);
Добавил в View/Register

2023-08-03 08:29 UTC, ArtCrafter2999 approved these changes

2023-08-03 08:29 UTC, merged