Upgrade ChatHub
SparkChats/API pull request #16
Opened 2023-08-07 16:11 UTC by Grabtot

closes #14

2023-08-07 20:05 UTC, ArtCrafter2999 requested changes
Трошки повиправляти

2023-08-07 20:05 UTC, ArtCrafter2999 commented on Application/Messages/AddMessageRequest/AddMessageRequestHandler.cs
> +            PrivateChat? chat = await _context.PrivateChats
ChatId може вказувати не тільки на PrivateChat, так що краще чат витаскувати з таблиці Chats

2023-08-07 20:05 UTC, ArtCrafter2999 commented on DataAccess/DesignTimeDbContextFactory.cs
>          optionsBuilder.UseSqlServer(configuration.GetConnectionString("Auth"));
Поміняй Auth на SqlServer

2023-08-07 20:05 UTC, ArtCrafter2999 commented on WebApi/Hubs/ChatHub.cs
> +    private int UserId => int.Parse(Context.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value
це нормально якщо воно буде викликати цю строку при кожному зверненні?

2023-08-07 20:05 UTC, ArtCrafter2999 commented on WebApi/Hubs/ChatHub.cs
> +            if (message.Chat is PrivateChat chat)
Треба зробити перевірку: Якщо повідомлення прийшло в канал а не в приватний чат, то розсилати учасникам серверу

2023-08-08 12:57 UTC, Grabtot commented on WebApi/Hubs/ChatHub.cs
> +    private int UserId => int.Parse(Context.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value
```suggestion
    private int UserId =>Parse(Context.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value
```

2023-08-08 13:29 UTC, ArtCrafter2999 approved these changes

2023-08-08 13:42 UTC, merged