Mongo db implementation
SparkChats/API pull request #36
Opened 2023-08-26 11:25 UTC by ArtCrafter2999

2023-08-27 14:40 UTC, Grabtot requested changes
Надо сделать так, чтобы тесты работали и здесь, разобраться с Identity контекстом и пофиксить ошибки

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/Channels/CreateChannel/CreateChannelRequestHandler.cs
> +            Server server = await Context.FindSqlByIdAsync<Server>(request.ServerId, cancellationToken, "ServerProfile");
Неправильные импроты
```suggestion
            Server server = await Context.FindSqlByIdAsync<Server>(request.ServerId, cancellationToken, "ServerProfiles","ServerProfiles.User");
```

2023-08-27 14:40 UTC, Grabtot commented on Application/Models/Role.cs
> +public class Role : IdentityRole<ObjectId>
Если роли остаются в sql, id должен быть int
```suggestion
public class Role : IdentityRole<int>
```

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/Messages/EditMessage/EditMessageRequestHandler.cs
> +            await Context.Messages.UpdateOneAsync(
Может обновление текста и и вложений делать в одном UpdateOneAsync?

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/Messages/RemoveAllReactions/RemoveAllReactionsRequestHandler.cs
> +            Context.Messages.UpdateOneAsync(
Надо добавить await
```suggestion
           await Context.Messages.UpdateOneAsync(
```

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/PrivateChats/CreatePrivateChat/CreatePrivateChatRequestHandler.cs
> +            User owner = await Context.FindSqlByIdAsync<User>(UserId, cancellationToken);
Не надо получать owner по UserId, чтобы получить Id текущего юзера 
```suggestion
```

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/PrivateChats/CreatePrivateChat/CreatePrivateChatRequestHandler.cs
>                  OwnerId = owner.Id
Тут можно использовать просто ```UserId ``` 
```suggestion
                OwnerId = UserId
```

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/PrivateChats/RenamePrivateChat/RenamePrivateChatRequestHandler.cs
> +            Context.PrivateChats.UpdateOneAsync(
Надо добавить await
```suggestion
           await Context.PrivateChats.UpdateOneAsync(
```

2023-08-27 14:40 UTC, Grabtot commented on Application/Commands/Servers/DeleteServer/DeleteServerRequestHandler.cs
> +            await Context.Channels.DeleteManyAsync(Builders<Channel>.Filter.Eq(c => c.ServerId, request.ServerId),null, cancellationToken);
Надо ещё все роли и server profile удалить

2023-08-27 14:40 UTC, Grabtot commented on Application/Queries/GetPrivateChats/GetPrivateChatLookUpDto.cs
Этот файл уже не нужен

2023-08-27 14:40 UTC, Grabtot commented on Application/Queries/GetServerDetails/ServerDetailsDto.cs
> +        public List<Channel> Channels { get; set; }
Тут лучше оставить lookup, а не передавать канал целиком для списка

2023-08-27 14:40 UTC, Grabtot commented on Application/Queries/GetServers/GetServersRequestHandler.cs
> +                    new GetServerLookupDto
Это лучше сделать с помощью AutoMapper

2023-08-27 14:40 UTC, Grabtot commented on DataAccess/AppDbContext.cs
> +        public async Task<TEntity> FindByIdAsync<TEntity>(ObjectId id, CancellationToken cancellationToken = default)
Тут надо использовать switch вместо if 
Пример:
```c#
            Type type = typeof(TEntity);
            TEntity? entity = null;

            entity = type.Name switch
            {
                nameof(Chat) => await FindByIdAsync(Chats, id, cancellationToken) as TEntity,
                nameof(PrivateChat) => await FindByIdAsync(PrivateChats, id, cancellationToken) as TEntity,
                nameof(Channel) => await FindByIdAsync(Channels, id, cancellationToken) as TEntity,
                nameof(Message) => await FindByIdAsync(Messages, id, cancellationToken) as TEntity,
                nameof(Media) => await FindByIdAsync(Media, id, cancellationToken) as TEntity,
                nameof(Server) => await FindByIdAsync(Servers, id, cancellationToken) as TEntity,
                _ => throw new InvalidOperationException($"Unhandled entity type: {type.Name}"),
            };
            return entity ?? throw new EntityNotFoundException($"{type.Name} {id} not found");
```

2023-08-27 14:40 UTC, Grabtot commented on DataAccess/AppDbContext.cs
> +    public class AppDbContext : DbContext, IAppDbContext
Чтобы Identity работало, контекст должен наследоваться от ``` IdentityDbContext<TUser, TRole, TKey>```
Надо либо наследоваться от этого класса, либо перенести юзеров и роли в отдельный контекст

2023-08-27 14:40 UTC, Grabtot commented on DataAccess/DesignTimeDbContextFactory.cs
>          optionsBuilder.UseSqlServer(configuration.GetConnectionString("SqlServer"));
Надо добавить проверку на null, чтобы не было варнинга

2023-08-27 14:40 UTC, Grabtot commented on Tests/Common/TestDbContextFactory.cs
Надо использовать mock вместо настоящей db

2023-08-27 14:40 UTC, Grabtot commented on Tests/Messages/Commands/AddMessageTests.cs
> +            CreateDatabase();
```    CreateDatabase();``` тоже часть Arrange

2023-08-28 08:25 UTC, ArtCrafter2999 commented on Application/Commands/Channels/CreateChannel/CreateChannelRequestHandler.cs
> +            Server server = await Context.FindSqlByIdAsync<Server>(request.ServerId, cancellationToken, "ServerProfile");
Ні... User'a не треба підтягувати. Через include треба підтягувати тільки списки, бо з цим крашиться

2023-08-28 08:30 UTC, ArtCrafter2999 commented on Application/Commands/Messages/EditMessage/EditMessageRequestHandler.cs
> +            await Context.Messages.UpdateOneAsync(
Тут дивись, мені треба спочатку витягнути ті атачменти, які з посиланнь в тексті, відповідно я цю команду поєдную з оновленням тексту. А коли воно оновилося я додаю до оригінальних атачментів ті які можливо знову з'явилися в тексті

2023-08-28 08:33 UTC, ArtCrafter2999 commented on Application/Commands/Messages/EditMessage/EditMessageRequestHandler.cs
> +            await Context.Messages.UpdateOneAsync(
а хоча ти прав, я чогось не подумав що я можу цю перевірку зробити до оновлення бази

2023-08-28 08:35 UTC, ArtCrafter2999 commented on Application/Commands/PrivateChats/CreatePrivateChat/CreatePrivateChatRequestHandler.cs
> +            User owner = await Context.FindSqlByIdAsync<User>(UserId, cancellationToken);
Це відбувається в методі створення чату, відповідно Owner і буде юзер який відправив такий запит тобто той, якого ми отримуємо з UserId

2023-08-28 11:04 UTC, Grabtot commented on Application/Commands/Channels/CreateChannel/CreateChannelRequestHandler.cs
> +            Server server = await Context.FindSqlByIdAsync<Server>(request.ServerId, cancellationToken, "ServerProfile");
Без этого крашится, потому что в строчке 16 user - null

2023-08-28 11:09 UTC, Grabtot commented on Application/Commands/PrivateChats/CreatePrivateChat/CreatePrivateChatRequestHandler.cs
> +            User owner = await Context.FindSqlByIdAsync<User>(UserId, cancellationToken);
Так а зачем нам делать запрос в дб, чтобы получить owner, если мы используем его только для id?

2023-08-29 11:00 UTC, ArtCrafter2999 commented on Application/Queries/GetServers/GetServersRequestHandler.cs
> +                    new GetServerLookupDto
Ну спробуй, у мене не вийшло

2023-08-29 11:00 UTC, ArtCrafter2999 commented on Application/Queries/GetServerDetails/ServerDetailsDto.cs
> +        public List<Channel> Channels { get; set; }
А блін, я чогось подумав що попередній look up такий самий як і звичайний channel а не врахував що там ще від чата залишилося
Але в цьому не так багато значення, на 1 стрінгу і 10 цифр більше. 
Роби як хочеш

2023-08-29 11:00 UTC, ArtCrafter2999 commented on Application/Commands/PrivateChats/CreatePrivateChat/CreatePrivateChatRequestHandler.cs
> +            User owner = await Context.FindSqlByIdAsync<User>(UserId, cancellationToken);
А, щось протупив, ти прав

2023-08-29 11:06 UTC, Grabtot approved these changes
Finally its done

2023-08-29 11:06 UTC, Grabtot commented on Application/Commands/Channels/CreateChannel/CreateChannelRequestHandler.cs
> +            Server server = await Context.FindSqlByIdAsync<Server>(request.ServerId, cancellationToken, "ServerProfile");
Теперь работает

2023-08-29 11:06 UTC, Grabtot commented on Application/Models/Channel.cs
> +    [DefaultValue("5f95a3c3d0ddad0017ea9291")]
Может это должно быть имя канала?
```suggestion
    [DefaultValue("Test Channel")]
```

2023-08-29 11:06 UTC, Grabtot commented on Application/Queries/GetServerDetails/ServerDetailsDto.cs
> +        public List<Channel> Channels { get; set; }
Ок, пусть так будет

2023-08-29 11:07 UTC, ArtCrafter2999 commented on Application/Models/Channel.cs
> +    [DefaultValue("5f95a3c3d0ddad0017ea9291")]
блін, як воно сюди взагалі потрапило, я ж робив це в іншій гілці
так, я переплутав

2023-08-29 11:12 UTC, merged