Adjust api
SparkChats/API pull request #79
Opened 2023-09-21 13:06 UTC by ArtCrafter2999

part of #68

2023-09-21 16:52 UTC, Grabtot requested changes

2023-09-21 16:52 UTC, Grabtot commented on Application/GroupChats/Commands/RenameGroupChat/RenameGroupChatCommand.cs
> +        public string? NewTitle { get; init; }
Ты сделал это nullable чтобы можно было удалить имя?

2023-09-21 16:52 UTC, Grabtot commented on Application/HubClients/Connections/Connect/ConnectRequestHandler.cs
> +                await new NotifyUserUpdatedRequestHandler(_hubContextProvider, Context, UserProvider, Mapper)
Внутри одной команды нельзя вызывать другую. Их можно вызывать по очереди (как в контролерах)

2023-09-21 16:52 UTC, Grabtot commented on Application/HubClients/PrivateChats/PrivateChatRemoved/NotifyPrivateChatRemovedQueryHandler.cs
> +    public class NotifyPrivateChatRemovedRequestHandler : HubRequestHandlerBase, IRequestHandler<NotifyPrivateChatRemovedQuery>
Теперь у нас все IRequest называются либо command, если в процессе меняются какие-то данные, либо query, если нет

2023-09-21 16:52 UTC, Grabtot commented on Application/Users/Commands/ChangeStatusRequest/ChangeStatusRequest.cs
> +    public record ChangeStatusRequest : IRequest
тоже неправильное название

2023-09-21 16:52 UTC, Grabtot commented on Application/Users/Queries/GetUserIdFromUserName/GetUserIdFromUserNameQueryValidator.cs
> +                .WithMessage("Username is required.")
Если что оно само кидает нормальные сообщения по базовым требованиям. Сообщения нужно писать только к регуляркам и кастомной логике.

2023-09-21 16:52 UTC, Grabtot commented on DataAccess/DependencyInjection.cs
> +                options.LogTo(s => { }, LogLevel.None);
Не надо выключать логи, они мне нужны

2023-09-21 16:52 UTC, Grabtot commented on WebApi/Controllers/MediaController.cs
> +        [Route("{id}.{ext}")]
Не надо отдельно писать атрибут ```Route```. Путь для роута можно указать в конструкторе ```HttpGet```
```c#
[HttpGet("{id}.{ext}"]
```

2023-09-21 16:52 UTC, Grabtot commented on WebApi/Controllers/UsersController.cs
> +            try
В методах контроллера не надо ловить исключения, этим занимается ```ExceptionFilter```

2023-09-21 16:52 UTC, Grabtot commented on WebApi/Controllers/UsersController.cs
> +            return Ok(await Mediator.Send(new GetUserIdFromUserNameQuery() { UserName = userName }));
Лучше включить это в метод ```GetUser(Guid? userId = null, string? serverId = null)```

2023-09-21 16:52 UTC, Grabtot commented on Application/Common/Interfaces/IAuthorizedUserProvider.cs
> +        void SetUser(ClaimsPrincipal user);
Зачем это? ClaimsPrincipal меняются автоматически в зависимости от токена в хэдерах запроса

2023-09-21 16:54 UTC, ArtCrafter2999 commented on Application/GroupChats/Commands/RenameGroupChat/RenameGroupChatCommand.cs
> +        public string? NewTitle { get; init; }
Ну якщо у чата немає ім'я, то він відображає дісплей нейми юзерів через кому, але я тільки що помітив що в діскорді не можна поставити чат без назви, тож не знаю, чи залишити чи змінити?

2023-09-21 16:58 UTC, ArtCrafter2999 commented on Application/HubClients/Connections/Connect/ConnectRequestHandler.cs
> +                await new NotifyUserUpdatedRequestHandler(_hubContextProvider, Context, UserProvider, Mapper)
ну просто вона умовна, але добре, винесу в хаб

2023-09-21 16:59 UTC, ArtCrafter2999 commented on Application/HubClients/PrivateChats/PrivateChatRemoved/NotifyPrivateChatRemovedQueryHandler.cs
> +    public class NotifyPrivateChatRemovedRequestHandler : HubRequestHandlerBase, IRequestHandler<NotifyPrivateChatRemovedQuery>
назву файлу поміняв, а назву класу забув 😅

2023-09-21 17:06 UTC, ArtCrafter2999 commented on Application/Common/Interfaces/IAuthorizedUserProvider.cs
> +        void SetUser(ClaimsPrincipal user);
В життєвому циклі ChatHub'a немає httpContext і я не знайшов способу отримати ClaimsPrincipal через DependencyInjection
![image](https://github.com/SparkChats/API/assets/92592800/8819eace-e954-4af4-8ace-90d916bee382)
Контекст в цьому випадку є прямим наслідником від хаба

2023-09-22 09:56 UTC, Grabtot approved these changes

2023-09-22 09:59 UTC, Grabtot commented on Application/GroupChats/Commands/RenameGroupChat/RenameGroupChatCommand.cs
> +        public string? NewTitle { get; init; }
Пусть будет

2023-09-22 10:00 UTC, merged