Database
SparkChats/API pull request #8
Opened 2023-07-28 17:36 UTC by ArtCrafter2999

#4

2023-07-28 20:32 UTC, Grabtot requested changes
Надо поправить места, где ты в наследниках перековываешь Id и поправить моменты о которых я в комментах написал

2023-07-28 20:32 UTC, Grabtot commented on Application/Models/Attachment.cs
> +    public string Path { get; set; }
Path это как Url?

2023-07-28 20:32 UTC, Grabtot commented on Application/Models/Channel.cs
> +    public int Id { get; set; }
Реально перекрывает(как пишет в варнинге ниже)

2023-07-28 20:32 UTC, Grabtot commented on Application/Models/PrivateChat.cs
> +    public int Id { get; set; }
Тут тоже перекрывает

2023-07-28 20:32 UTC, Grabtot commented on DataAccess/AppDbContext.cs
> +        Database.EnsureCreated();
Всё-таки лучше убрать ` Database.EnsureCreated();`

2023-07-28 20:32 UTC, Grabtot commented on DataAccess/DesignTimeDbContextFactory.cs
> +            .Build();
Лучше не хардкодить путь к файлу, а внедрить его через DI

2023-07-28 20:32 UTC, Grabtot commented on DataAccess/DesignTimeDbContextFactory.cs
Не нашёл где ты используешь этот класс

2023-07-29 09:33 UTC, ArtCrafter2999 commented on DataAccess/DesignTimeDbContextFactory.cs
> +            .Build();
In the DesignTimeDbContextFactory, you won't be able to directly inject IConfiguration through the constructor, as the IDesignTimeDbContextFactory interface only expects a parameterless constructor.

However, you can still access the configuration in the CreateDbContext method by building the configuration manually using the ConfigurationBuilder, just like you did in your previous AppDbContext class.

2023-07-29 09:33 UTC, ArtCrafter2999 commented on DataAccess/DesignTimeDbContextFactory.cs
Він використовується при будові бази даних (міграції і все таке)

2023-07-29 09:42 UTC, Grabtot approved these changes
Well done

2023-07-29 09:44 UTC, merged